<a href="https://colab.research.google.com/github/febinchundakkattiil/Febin-s-Personal-Wesbsite/blob/master/array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
ar1 = np.array([1,2,3,4,5,6,7,8,9])
ar1


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ar1 = np.arange(10)
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_list = [1,2,3,4]
arr = np.array(my_list)
arr

array([1, 2, 3, 4])